version: "3.8"

services:
    mysql-source:
      image: mysql:8.0
      container_name: mysql-source
      restart: always
      env_file:
        - ./mysql-source/env.list
      volumes:
        - ./mysql-source/my.cnf:/etc/mysql/conf.d/my.cnf
        - mysql_source_data:/var/lib/mysql
      ports:
        - "3307:3306"

    mysql-target:
      image: mysql:8.0
      container_name: mysql-target
      restart: always
      env_file:
        - ./mysql-target/env.list
      volumes:
        - ./mysql-target/my.cnf:/etc/mysql/conf.d/my.cnf
        - mysql_target_data:/var/lib/mysql
      ports:
        - "3308:3306"

    flink-jobmanager:
      image: flink:1.20.3-scala_2.12-java8
      container_name: flink-jobmanager
      environment:
        - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      command: jobmanager
      ports:
        - "8081:8081"
      volumes:
        - ./flink/usrlib:/opt/flink/usrlib

    flink-taskmanager:
      image: flink:1.20.3-scala_2.12-java8
      container_name: flink-taskmanager
      depends_on:
        - flink-jobmanager
      environment:
        - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
      command: taskmanager
      volumes:
        - ./flink/usrlib:/opt/flink/usrlib

volumes:
    mysql_source_data:
    mysql_target_data: